const fs=require('fs'),vm=require('vm'),assert=require('assert');
const {chromium}=require('C:/Users/TukitoPT/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
(async()=>{
for(const file of ['app.html','mapa.html','comparar.html','calculadora.html']){const html=fs.readFileSync(__dirname+'/'+file,'utf8');for(const m of html.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/g))if(m[1].trim())new vm.Script(m[1],{filename:file});}
for(const f of fs.readdirSync(__dirname).filter(f=>f.endsWith('.js')))new vm.Script(fs.readFileSync(__dirname+'/'+f,'utf8'));
const c=vm.createContext({console,TextDecoder});vm.runInContext(fs.readFileSync(__dirname+'/shared.js','utf8'),c);
assert.equal(c.parseCsvGenerico('a;b\n1;"duas\nlinhas"',['a','b']).rows[0].b,'duas\nlinhas');
assert.equal(c.parseCsvGenerico('a;b\n1;"aberto',['a','b']).erro,'semdados');
const browser=await chromium.launch({headless:true,channel:"msedge"});const context=await browser.newContext({viewport:{width:390,height:844}});const page=await context.newPage();const errors=[];page.on('pageerror',e=>{errors.push(e.message);console.log('pageerror',e.message)});page.on('console',m=>console.log('browser:',m.text()));page.on('dialog',d=>d.dismiss());
console.log('browser ready');await page.goto('http://127.0.0.1:8765/app.html');console.log('page',await page.evaluate(()=>({sw:'serviceWorker' in navigator, state:document.readyState})));await page.waitForFunction(()=>navigator.serviceWorker.controller,{},{timeout:15000});console.log('sw ready');await page.reload();
await page.locator('#btnLoadCsv').setInputFiles('C:/Users/TukitoPT/Desktop/RL_ENC_PON_92SF01_113434.csv');await page.waitForFunction(()=>csvData.length===2062);
await page.locator('#quick-search').fill('PDO');await page.locator('#quick-options button').first().click();await page.waitForFunction(()=>document.getElementById('textResult').textContent.length>30);
assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:__dirname+'/preview-mobile.png',fullPage:true});
await page.locator('#theme-toggle').click();assert.equal(await page.locator('html').getAttribute('data-theme'),'light');
await page.setViewportSize({width:1366,height:900});await page.waitForTimeout(250);await page.screenshot({path:__dirname+'/preview-desktop.png',fullPage:true});
await page.goto('http://127.0.0.1:8765/comparar.html');const march=fs.readdirSync('C:/Users/TukitoPT/Desktop').find(n=>n.normalize('NFC')==='92SF01 março 2026.csv');await page.locator('#btnLoadAntigo').setInputFiles('C:/Users/TukitoPT/Desktop/'+march);await page.locator('#btnLoadNovo').setInputFiles('C:/Users/TukitoPT/Desktop/RL_ENC_PON_92SF01_113434.csv');await page.waitForFunction(()=>antigo&&novo);await page.locator('#btnComparar').click();assert((await page.locator('#comparResult').innerText()).includes('Ocupante alterado · 26'));const counts=await page.evaluate(()=>{const r=compararCsvs(antigo.rows,novo.rows);return [r.ocupanteAlterado.length,r.portosAdicionados.length,r.portosRemovidos.length]});assert.deepEqual(counts,[26,73,58]);
await context.setOffline(true);await page.goto('http://127.0.0.1:8765/app.html?pdo=teste');await page.waitForFunction(()=>csvData.length===2062);await context.setOffline(false);
for(const width of [320,390,430,768,1366]){await page.setViewportSize({width,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'Overflow '+width);}
await page.goto('http://127.0.0.1:8765/calculadora.html');await page.locator('#editFibra').fill('288');await page.locator('#btnCalcularCor').click();assert((await page.locator('#textCorResult').innerText()).includes('Tubo 24'));await page.locator('#editFibra').fill('1.5');await page.locator('#btnCalcularCor').click();assert.equal(await page.locator('#textCorResult').innerText(),'');assert((await page.locator('#colorError').innerText()).includes('inteiro'));
await page.goto('http://127.0.0.1:8765/app.html');await page.locator('#quick-search').fill('PDO');await page.locator('#quick-search').press('ArrowDown');await page.locator('#quick-search').press('Enter');assert((await page.locator('#textResult').innerText()).length>30);await page.locator('#btnLimparTudo').click();assert.equal(await page.locator('#quick-search').inputValue(),'');assert.equal(await page.locator('#textResult').innerText(),'');
await page.locator('#btnLoadCsv').setInputFiles({name:'invalid.csv',mimeType:'text/csv',buffer:Buffer.from('wrong;columns\n1;2')});await page.waitForFunction(()=>document.getElementById('importFeedback').textContent.includes('Continua ativo'));assert.equal(await page.evaluate(()=>csvData.length),2062);
await page.goto('http://127.0.0.1:8765/comparar.html');await page.locator('#btnLoadAntigo').setInputFiles('C:/Users/TukitoPT/Desktop/'+march);await page.locator('#btnLoadNovo').setInputFiles('C:/Users/TukitoPT/Desktop/RL_ENC_PON_92SF01_113434.csv');await page.waitForFunction(()=>antigo&&novo);await page.locator('#btnComparar').click();await page.locator('#btnLoadNovo').setInputFiles({name:'invalid.csv',mimeType:'text/csv',buffer:Buffer.from('wrong;columns\n1;2')});await page.waitForFunction(()=>novo===null);assert(await page.locator('#btnComparar').isDisabled());assert.equal(await page.locator('#comparResult').innerText(),'');
await page.goto('http://127.0.0.1:8765/mapa.html');for(const width of [320,390,1366]){await page.setViewportSize({width,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'Map overflow '+width);}
await context.setOffline(true);await page.goto('http://127.0.0.1:8765/calculadora.html');await page.locator('#editFibra').fill('24');await page.locator('#btnCalcularCor').click();assert((await page.locator('#textCorResult').innerText()).includes('Tubo 2'));const downloadPromise=page.waitForEvent('download');await page.locator('#btnPDF').click();const download=await downloadPromise;assert.equal(download.suggestedFilename(),'Tabela_Fibras_Opticas.pdf');assert.equal(await download.failure(),null);await context.setOffline(false);
assert.deepEqual(errors,[]);console.log('PASS: syntax, CSV multiline/malformed, import, quick search, comparison 26/73/58, themes, offline restore, viewport widths 320–1366.');await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});

